# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  scheme='BattleBlocksScorecard'
  build_configuration="Release"

  desc "Builds an ipa file"
  lane :build do
    # Build IPA
    gym(
      configuration: build_configuration,
      scheme: scheme,
      output_name: "BattleBlocksScorecard.ipa",
      include_symbols: true,
      include_bitcode: true,
      export_method: "app-store",
      clean: true,
      archive_path: "./builds/fastlane_output/BattleBlocksScorecard.xcarchive",
      output_directory: "./builds/fastlane_output/",
      export_options: {
        method: "app-store",
      }
    )
  end

  lane :release do
    api_key = app_store_connect_api_key(
      key_id: "S48B7KT5CP",
      issuer_id: "69a6de79-4e66-47e3-e053-5b8c7c11a4d1",
      key_filepath: "./AuthKey_S48B7KT5CP.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false, # optional but may be required if using match/sigh
    )
  
    pilot(
      api_key: api_key,
      ipa: "./builds/fastlane_output/BattleBlocksScorecard.ipa",
      skip_waiting_for_build_processing: true,
    )
  end
end
